### ISSUE TITLE
invalid toolchain name: 'esp'

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [bjoernQ/bleps-esp32-rust-std#1]
When I clone this repo and run `cargo run` I get this error:
```
error: in /var/home/rajas/Documents/bleps-esp32-rust-std/rust-toolchain.toml: invalid toolchain name: 'esp'
```

**Comment by bjoernQ** [comment]
ESP32 is an Xtensa-based microcontroller. Since Xtensa architecture is not yet supported by the mainline Rust compiler you would need the `esp` toolchain (a fork of the Rust compiler with Xtensa support) - see https://esp-rs.github.io/book/installation/riscv-and-xtensa.html
